/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#adaaaa',
        'primary-fixed-dim': '#fe5e1e',
        'surface-container-lowest': '#000000',
        'primary-fixed': '#ff7948',
        'tertiary-fixed': '#6bfe9c',
        'on-secondary-fixed': '#403f3f',
        'primary-container': '#ff7948',
        'surface-tint': '#ff9069',
        'primary': '#ff9069',
        'primary-dim': '#ff7441',
        'secondary': '#e5e2e1',
        'inverse-on-surface': '#565555',
        'outline-variant': '#484847',
        'on-tertiary-fixed': '#004a23',
        'tertiary-dim': '#5bef90',
        'error': '#ff716c',
        'secondary-dim': '#d7d4d3',
        'tertiary-container': '#6bfe9c',
        'tertiary': '#c3ffcd',
        'surface-container-highest': '#262626',
        'on-tertiary-container': '#005f2f',
        'error-container': '#9f0519',
        'on-surface': '#ffffff',
        'surface-dim': '#0e0e0e',
        'on-secondary': '#525151',
        'surface-variant': '#262626',
        'inverse-primary': '#ac3600',
        'secondary-fixed-dim': '#d7d4d3',
        'outline': '#767575',
        'on-secondary-fixed-variant': '#5c5b5b',
        'error-dim': '#d7383b',
        'surface-bright': '#2c2c2c',
        'secondary-fixed': '#e5e2e1',
        'on-primary-fixed-variant': '#551600',
        'on-error-container': '#ffa8a3',
        'on-primary-container': '#451000',
        'surface-container-high': '#201f1f',
        'on-background': '#ffffff',
        'on-tertiary': '#006834',
        'on-primary-fixed': '#000000',
        'on-tertiary-fixed-variant': '#006a35',
        'secondary-container': '#474646',
        'background': '#0e0e0e',
        'tertiary-fixed-dim': '#5bef90',
        'on-secondary-container': '#d2d0cf',
        'surface-container': '#1a1919',
        'surface': '#0e0e0e',
        'surface-container-low': '#131313',
        'on-error': '#490006',
        'inverse-surface': '#fcf9f8',
        'on-primary': '#591800',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['var(--font-body)', 'Manrope', 'sans-serif'],
        label: ['var(--font-body)', 'Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
