export const outlet = {
  name: 'P. Corner',
  tagline: 'Traditional Greek flavors, contemporary soul.',
  description: 'A mobile-first food outlet for quick takeaway and doorstep delivery.',
  addressLine: 'Cyprus',
  ownerName: 'Owner',
  ownerWhatsApp: '35799955764',
  takeawayTiming: '15:30 - 22:00',
  deliveryTiming: '18:00 - 21:00',
  closedDay: 'Tuesday',
  socials: [
    { label: 'Phone 1', handle: '99-955764' },
    { label: 'Phone 2', handle: '99-166646' },
  ],
  specialties: ['P Corner Special', 'Sheftalia', 'Halloumi Portion'],
};

export const menu = [
  {
    category: 'Starters',
    greek: 'Ορεκτικά',
    items: [
      { id: 'large-salad', name: 'Large Salad', greek: 'Σαλάτα μεγάλη', price: 5.0, note: 'Fresh Mediterranean seasonal greens.', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2000&auto=format&fit=crop' },
      { id: 'tuna-salad', name: 'Tuna Salad', greek: 'Τονοσαλάτα', price: 6.5, note: 'Premium tuna with crisp garden vegetables.', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=2000&auto=format&fit=crop' },
      { id: 'coleslaw', name: 'Coleslaw', price: 3.0, note: 'Classic cream.' },
      { id: 'tachini', name: 'Tachini', greek: 'Ταχίνι', price: 1.0, note: 'Authentic dip.' },
      { id: 'tirokafteri', name: 'Tirokafteri', greek: 'Τυροκαφτερή', price: 1.0, note: 'Spicy cheese dip.' },
      { id: 'tzatziki', name: 'Tzatziki', greek: 'Τζατζίκι', price: 1.0, note: 'Cool yogurt dip.' },
      { id: 'yoghurt', name: 'Yoghurt', greek: 'Γιαούρτι', price: 1.0, note: 'Plain Greek yoghurt.' },
    ],
  },
  {
    category: 'Burgers',
    greek: 'Χάμπουργκερ',
    note: '*Served with Chips',
    items: [
      { id: 'pork-burger', name: 'Pork Burger*', price: 6.0, note: '*Served with chips', image: 'https://images.unsplash.com/photo-1586816001966-79b736744398?q=80&w=2000&auto=format&fit=crop' },
      { id: 'beef-burger', name: 'Beef Burger*', price: 7.0, note: '*Served with chips', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=2000&auto=format&fit=crop' },
      { id: 'cheese-burger', name: 'Cheese Burger*', price: 6.0, note: '*Served with chips' },
      { id: 'chicken-burger', name: 'Chicken Burger*', price: 6.0, note: '*Served with chips' },
      { id: 'vegie-burger', name: 'Vegie Burger', price: 6.0, note: 'Plant-based patty' },
    ],
  },
  {
    category: 'Sandwiches',
    greek: 'Σάντουιτς',
    items: [
      { id: 'sandwich', name: 'Sandwich', price: 5.0, note: 'Bacon, ham, lountza, halloumi.' },
      { id: 'sandwich-chips', name: 'Sandwich & Chips', price: 6.0, note: 'With a side of chips.' },
      { id: 'hot-dog', name: 'Hot Dog', greek: 'Χοτ Ντόγκ', price: 3.5, note: 'Classic style.' },
      { id: 'hot-dog-chips', name: 'Hot Dog & Chips', price: 4.5, note: 'With a side of chips.' },
      { id: 'kebab-sandwich', name: 'Kebab', greek: 'Κεμπάπ', price: 5.0, note: 'In fresh bread.' },
    ],
  },
  {
    category: 'Portions',
    greek: 'Μερίδες',
    note: 'Includes Chips and Salad',
    items: [
      { id: 'portion-pork-kebab', name: 'Pork Kebab', greek: 'Σουβλάκι Χοιρινό', price: 10.0, note: 'With chips & salad.', image: 'https://images.unsplash.com/photo-1615967912423-edfa7a0bdf81?q=80&w=2000&auto=format&fit=crop' },
      { id: 'portion-chicken-kebab', name: 'Chicken Kebab', greek: 'Σουβλάκι Κοτόπουλο', price: 10.0, note: 'With chips & salad.', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2000&auto=format&fit=crop' },
      { id: 'portion-sheftalia', name: 'Sheftalia', greek: 'Σιεφταλιές', price: 10.0, note: 'With chips & salad.', image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?q=80&w=2000&auto=format&fit=crop' },
      { id: 'portion-mix', name: 'Mix', greek: 'Μιξ', price: 10.0, note: 'With chips & salad.', popular: true, image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=2000&auto=format&fit=crop' },
      { id: 'portion-chicken-doner', name: 'Chicken Doner', greek: 'Γύρος Κοτόπουλο', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-mixed-doner', name: 'Mixed Doner', greek: 'Γύρος Μιξ', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-pork-doner', name: 'Pork Doner', greek: 'Γύρος Χοιρινός', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-halloumi', name: 'Halloumi Portion', greek: 'Χαλλούμι μερίδα', price: 12.0, note: 'With chips & salad.' },
      { id: 'chicken-nuggets', name: 'Chicken Nuggets', greek: 'Κοτομπουκιές', price: 7.0, note: 'With chips & salad.' },
    ],
  },
  {
    category: 'Souvlaki & Doner',
    greek: 'Σουβλάκι και Γύρος',
    special: { name: 'P Corner Special', normalPrice: 5.0, largePrice: 8.0, note: 'Our signature creation with secret spice blend.' },
    items: [
      { id: 'souv-pork-kebab', name: 'Pork Kebab', greek: 'Σουβλάκι Χοιρινό', price: 6.0 },
      { id: 'souv-chicken-kebab', name: 'Chicken Kebab', greek: 'Σουβλάκι Κοτόπουλο', price: 6.5 },
      { id: 'souv-sieftalia', name: 'Sieftalia', greek: 'Σιεφταλιά', price: 6.0 },
      { id: 'souv-mix', name: 'Mix', greek: 'Μιξ', price: 6.0 },
      { id: 'souv-falafel', name: 'Falafel', greek: 'Φαλάφελ', price: 6.0 },
      { id: 'souv-chicken-doner', name: 'Chicken Doner', greek: 'Γύρος Κοτόπουλο', price: 6.0 },
      { id: 'souv-mixed-doner', name: 'Mixed Doner', greek: 'Γύρος Μιξ', price: 6.0 },
      { id: 'souv-pork-doner', name: 'Pork Doner', greek: 'Γύρος Χοιρινός', price: 6.0 },
      { id: 'souv-halloumi', name: 'Halloumi', greek: 'Χαλλούμι', price: 7.0 },
    ],
  },
  {
    category: 'Drinks',
    greek: 'Ποτά',
    items: [
      { id: 'soft-drinks', name: 'Soft Drinks 330ml', greek: 'Αναψυκτικά', price: 2.0 },
      { id: 'water', name: 'Water 0.5lt', greek: 'Νερό μικρό', price: 0.5 },
      { id: 'ice-tea', name: 'Ice Tea 330ml', greek: 'Παγωμένο Τσάι', price: 1.5 },
      { id: 'juices', name: 'Juices 250ml', greek: 'Χυμοί', price: 1.0 },
      { id: 'hell', name: 'Hell 250ml', price: 1.5 },
    ],
  },
  {
    category: 'Sides',
    greek: 'Διάφορα',
    items: [
      { id: 'small-chips', name: 'Small Portion Chips', greek: 'Μικρή μερίδα πατάτες', price: 2.0 },
      { id: 'large-chips', name: 'Large Portion Chips', greek: 'Μεγάλη μερίδα πατάτες', price: 3.0 },
      { id: 'xl-chips', name: 'XL Portion Chips', greek: 'XL Μερίδα πατάτες', price: 4.0 },
      { id: 'onion-rings', name: 'Onion Rings', greek: 'Ροδέλες κρεμμυδιού', price: 3.0 },
      { id: 'chips-cheese', name: 'Chips w/cheese', greek: 'Πατάτες με τυρί', price: 5.0 },
    ],
  },
];
