export const outlet = {
  name: 'P. Corner',
  tagline: 'Traditional Greek flavors, contemporary soul.',
  description: 'A mobile-first food outlet for quick takeaway and doorstep delivery.',
  addressLine: 'Cyprus',
  ownerName: 'Owner',
  ownerWhatsApp: '35799955764',
  takeawayTiming: '15:30 - 22:00',
  deliveryTiming: '18:00 - 21:00',
  closedDay: 'Tuesday',
  socials: [
    { label: 'Phone 1', handle: '99-955764' },
    { label: 'Phone 2', handle: '99-166646' },
  ],
  specialties: ['P Corner Special', 'Sheftalia', 'Halloumi Portion'],
};

export const menu = [
  {
    category: 'Starters',
    greek: 'Ορεκτικά',
    items: [
      { id: 'large-salad', name: 'Large Salad', greek: 'Σαλάτα μεγάλη', price: 5.0, note: 'Fresh Mediterranean seasonal greens.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcN_Gex9mWu90h15P0KtNi2i49YXn6DcpwIbz1Q044XgZ0HJuGvW4q6FtB_j8QdWT-jfrnb-eHZvfAAEPkkrFKfPtKWPhoY3OnaNHNuSqyPxapOWpjfep4mwmbv-EZ1fLgku9CtSBP0RsDL579QY0rxbP9t3tiePo36C5Ijb4t3X4sXFa3jktuH-zJBSAoDw05tKyUJWs0yPDlFSpIRy8W-Sa910hZ_83NGUaHkVCDsbnqrMlfNSrPBLpA3f51YciUDsdvu3NjyPk' },
      { id: 'tuna-salad', name: 'Tuna Salad', greek: 'Τονοσαλάτα', price: 6.5, note: 'Premium tuna with crisp garden vegetables.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDtOdopng7L0Q3wJwCbySBJVp12bOxsy2oFSxDy0P6Smc_dx2x1lucCjF9zysXHnf44o8XGhaqF9qRLZVm-9NEJCWU1JqlGPBYkBHyki1XwcBIo__oOb_LyKOCB1PVikmyi9RZs6armDD9Z1xkCT37qNssffUOKeplYihQbfeypKXzTKJexAgZdoOMZmSZ_ZDNXGWnBw2ipkmWurw46NuTX7NxEzj1TWfBQ1B7Blfa08agXjNM17nflOSwhwZJQ4vMzphsf0KAVnV0' },
      { id: 'coleslaw', name: 'Coleslaw', price: 3.0, note: 'Classic cream.' },
      { id: 'tachini', name: 'Tachini', greek: 'Ταχίνι', price: 1.0, note: 'Authentic dip.' },
      { id: 'tirokafteri', name: 'Tirokafteri', greek: 'Τυροκαφτερή', price: 1.0, note: 'Spicy cheese dip.' },
      { id: 'tzatziki', name: 'Tzatziki', greek: 'Τζατζίκι', price: 1.0, note: 'Cool yogurt dip.' },
      { id: 'yoghurt', name: 'Yoghurt', greek: 'Γιαούρτι', price: 1.0, note: 'Plain Greek yoghurt.' },
    ],
  },
  {
    category: 'Burgers',
    greek: 'Χάμπουργκερ',
    note: '*Served with Chips',
    items: [
      { id: 'pork-burger', name: 'Pork Burger*', price: 6.0, note: '*Served with chips', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCcPARTvgHJ8AbN8r2TZH05QCjUxj5s9QnEW2gjt3ntcKOlR7KCaHpcv09OXvpysDaS9ywod-4y4UavQHH_JLDS2fl2csJiMCLA6jTYPZkBWJh7XaAbusKmi-BPbauTwMliaSu-3-mUkB0eC--n-t49NYpAYAJh0LkYULjufBljJaieBIMMIl2tg2eya3rT6UYjXp5kQkdsodliE29_KaGApoEbbLHXbYoex9rUlbDP9JKib1rCFtFjf8Xfj2SqQEW6RQzbMNRrDEI' },
      { id: 'beef-burger', name: 'Beef Burger*', price: 7.0, note: '*Served with chips', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-pcYL0aOqiEkpH8_J3CZj1CnZjKb-DIK6sBB2wDu28uToi_RvYOi0bYaRG-PEPsbuf6C5Teb-01X2BblPA6HvVmySMw4KOGolnY1YpMlHnHj7NcTK9Q9u3LA93TxfxsKO6hd5pzQRNnD9m_Qns7WAvqssArW9X0QXpzMIIcPnfPOmR9qvKv7mqFNSEnvDGawC09wgM__v38rBZIYwpTgdfWrmXbyXQ60aouHEPZmgKtEBI4hrL_xZDa28u3d40ac5iEvhXhGs1B4' },
      { id: 'cheese-burger', name: 'Cheese Burger*', price: 6.0, note: '*Served with chips' },
      { id: 'chicken-burger', name: 'Chicken Burger*', price: 6.0, note: '*Served with chips' },
      { id: 'vegie-burger', name: 'Vegie Burger', price: 6.0, note: 'Plant-based patty' },
    ],
  },
  {
    category: 'Sandwiches',
    greek: 'Σάντουιτς',
    items: [
      { id: 'sandwich', name: 'Sandwich', price: 5.0, note: 'Bacon, ham, lountza, halloumi.' },
      { id: 'sandwich-chips', name: 'Sandwich & Chips', price: 6.0, note: 'With a side of chips.' },
      { id: 'hot-dog', name: 'Hot Dog', greek: 'Χοτ Ντόγκ', price: 3.5, note: 'Classic style.' },
      { id: 'hot-dog-chips', name: 'Hot Dog & Chips', price: 4.5, note: 'With a side of chips.' },
      { id: 'kebab-sandwich', name: 'Kebab', greek: 'Κεμπάπ', price: 5.0, note: 'In fresh bread.' },
    ],
  },
  {
    category: 'Portions',
    greek: 'Μερίδες',
    note: 'Includes Chips and Salad',
    items: [
      { id: 'portion-pork-kebab', name: 'Pork Kebab', greek: 'Σουβλάκι Χοιρινό', price: 10.0, note: 'With chips & salad.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYZyr9HojpihoEQAgpa976GeLgwwWudHKBM44c4bm5gN-rYB6COGOGDVq5nL2qq7suKRVMUF7lMRL_XlLaVeET3jBVnVQu1Ke_5cz4CFd9Qv0DtAg3o2WQDm2yC39Aju_PewZr0fbvNHE4s657CiNR-k-pIuLkRboIzGw83x7N5bSgPuz0BHRLWMjPbOZNu9BJ1vHI4U2rJw2XM_-5KCVlyRbUh7vxdY7nDkPCRBUQj2rPczzwlqgQQoOUgvSARHncQzZIbcPdHoU' },
      { id: 'portion-chicken-kebab', name: 'Chicken Kebab', greek: 'Σουβλάκι Κοτόπουλο', price: 10.0, note: 'With chips & salad.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNGhWxV2co2WjeERaugoo8h6Om60-ahnTfrKF6zz3tA8zKFWH4lZrlv4XjO0XIixSUnUTKd8WlZ2sifmrzcezTDl-0BxPvMSBI3o8RJHqZLoGutGh92qeJq-PTadrOeQFUaMfiqTtba79O2nOSEUyGJU3Cwa9zpiNWFAGj0q6-WUvgAsPdeDwQYUAUd1ce3XaQsQM4gCkGjDl1CWKJr2KKTbiiK5dv9EgC2ejuPvS3DAJ1W6k1a9dbNQQ_UiG2zz48Toh5GmHu7fE' },
      { id: 'portion-sheftalia', name: 'Sheftalia', greek: 'Σιεφταλιές', price: 10.0, note: 'With chips & salad.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZ3-Df6xsRteI99dAJnNglUBPfjcjFQHH-WJHjuiIn9E_rpwQctfQnmseK3jP7TNT1JmfQdDH0wUesDf4f3BU2uJAU5ev4VowUjfMLLNKuUd-fG_fcelSphw7wAC6ZO32lkhgnU2lgrnACLtNETbInyzPSxavX8odGeFgxs9J4iVWypyG2xFVilJYQ93fjTMkJ94huUt1Rl_oei2W-rS3-0QgJ83ySdqMkeHqsoirY34VcAKrQtIpIkc_hSRJpzB62-KCDr0sqSPQ' },
      { id: 'portion-mix', name: 'Mix', greek: 'Μιξ', price: 10.0, note: 'With chips & salad.', popular: true, image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAijtVEtR4RwEeK_0X9VK5mdJsicrgB8ciIKYtjUk-oItrExyrr5dP8NX5YSyxKFlr_cqrkP2bvSMJhqCgNp1md1r9-dizq_CwaaN-IKqW0yqXCoka2b8-uWHLzvU4myr9ov6mO-VBtFXZonJBEvtRBBcNnTad9b4QmwMl6vrtak_4jmjw35grp70Wvh524H65ziRMj7Xn_GtQZ4IKX7FEfAopOH58p7vNLbedYKoxKEAszv8rHxO6t9IUVGj_cRYcaut34Kdq_lik' },
      { id: 'portion-chicken-doner', name: 'Chicken Doner', greek: 'Γύρος Κοτόπουλο', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-mixed-doner', name: 'Mixed Doner', greek: 'Γύρος Μιξ', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-pork-doner', name: 'Pork Doner', greek: 'Γύρος Χοιρινός', price: 10.0, note: 'With chips & salad.' },
      { id: 'portion-halloumi', name: 'Halloumi Portion', greek: 'Χαλλούμι μερίδα', price: 12.0, note: 'With chips & salad.' },
      { id: 'chicken-nuggets', name: 'Chicken Nuggets', greek: 'Κοτομπουκιές', price: 7.0, note: 'With chips & salad.' },
    ],
  },
  {
    category: 'Souvlaki & Doner',
    greek: 'Σουβλάκι και Γύρος',
    special: { name: 'P Corner Special', normalPrice: 5.0, largePrice: 8.0, note: 'Our signature creation with secret spice blend.' },
    items: [
      { id: 'souv-pork-kebab', name: 'Pork Kebab', greek: 'Σουβλάκι Χοιρινό', price: 6.0 },
      { id: 'souv-chicken-kebab', name: 'Chicken Kebab', greek: 'Σουβλάκι Κοτόπουλο', price: 6.5 },
      { id: 'souv-sieftalia', name: 'Sieftalia', greek: 'Σιεφταλιά', price: 6.0 },
      { id: 'souv-mix', name: 'Mix', greek: 'Μιξ', price: 6.0 },
      { id: 'souv-falafel', name: 'Falafel', greek: 'Φαλάφελ', price: 6.0 },
      { id: 'souv-chicken-doner', name: 'Chicken Doner', greek: 'Γύρος Κοτόπουλο', price: 6.0 },
      { id: 'souv-mixed-doner', name: 'Mixed Doner', greek: 'Γύρος Μιξ', price: 6.0 },
      { id: 'souv-pork-doner', name: 'Pork Doner', greek: 'Γύρος Χοιρινός', price: 6.0 },
      { id: 'souv-halloumi', name: 'Halloumi', greek: 'Χαλλούμι', price: 7.0 },
    ],
  },
  {
    category: 'Drinks',
    greek: 'Ποτά',
    items: [
      { id: 'soft-drinks', name: 'Soft Drinks 330ml', greek: 'Αναψυκτικά', price: 2.0 },
      { id: 'water', name: 'Water 0.5lt', greek: 'Νερό μικρό', price: 0.5 },
      { id: 'ice-tea', name: 'Ice Tea 330ml', greek: 'Παγωμένο Τσάι', price: 1.5 },
      { id: 'juices', name: 'Juices 250ml', greek: 'Χυμοί', price: 1.0 },
      { id: 'hell', name: 'Hell 250ml', price: 1.5 },
    ],
  },
  {
    category: 'Sides',
    greek: 'Διάφορα',
    items: [
      { id: 'small-chips', name: 'Small Portion Chips', greek: 'Μικρή μερίδα πατάτες', price: 2.0 },
      { id: 'large-chips', name: 'Large Portion Chips', greek: 'Μεγάλη μερίδα πατάτες', price: 3.0 },
      { id: 'xl-chips', name: 'XL Portion Chips', greek: 'XL Μερίδα πατάτες', price: 4.0 },
      { id: 'onion-rings', name: 'Onion Rings', greek: 'Ροδέλες κρεμμυδιού', price: 3.0 },
      { id: 'chips-cheese', name: 'Chips w/cheese', greek: 'Πατάτες με τυρί', price: 5.0 },
    ],
  },
];
